### PR TITLE
Update Launch to support AWS EFS AZ's

### PR DESCRIPTION
**Pull request by chrisurwin**
Add line to allow for enumeration of a host value to support AWS EFS and availability zones which are published with a format of 
$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).xxx.efs.eu-west-1.amazonaws.com

If this is just a plain dns entry then it will not make any changes

### CODE REVIEW

**Comment by vincent99** [comment]
This seems rather arbitrary code execution vulnerability-ey...

**Comment by tholcman** [comment]
Vulnerable? Maybe, but does it have any meaning in Docker/Rancher environment where the person or process which starts the container (sets metadata) has full access and full control of everything related?

Can we add boolean envinronment variable EVAL_NFS_SERVER=1/0

or how to set dynamic server endpoint?

This is really useful for AWS EFS!

**Comment by chrisurwin** [comment]
Unfortunately I actually agree with Vincent, so to that end I've started a catalog entry to add a convoy-efs.
Add the following catalog https://github.com/chrisurwin/catalog.git 

I need to get the graphic updated but it appears to work, is more tailored to EFS and is less vulnerable

**Comment by cjellick** [comment]
LGTM

**Comment by schuylr** [comment]
@chrisurwin I like your catalog entry and I'm going to use it - I do have one small caveat: since EFS is regionally restricted and only available in a few regions, could it be possible to add a host scheduling label entry to the entry? I'm running an environment with cross-region support and want to support a portion of my cluster only with EFS, and prevent the rest from trying to unsuccessfully run the containers.

**Comment by chrisurwin** [comment]
@schuylr I'll take a look at it

**Comment by andyshinn** [comment]
Can someone explain how this patch is used? Do we somehow change the command to command: volume-agent-efs? Then what goes in the NFS server section?

**Comment by andyshinn** [comment]
Excuse my ignorance. I didn't realize it is a completely separate catalog entry called Convoy EFS!

**Pull request merged**
