### PR TITLE
Building improvement

### PR DESCRIPTION
**Pull request by yasker**
@cjellick 

Various of building improvement includes:
1. Use trash instead of godeps for dependency management.
2. Use dapper for building. Now the project can be built with `make`
3. Improve container building. Now the container can be built with `make image`.

Please review, thanks!

### CODE REVIEW

**Comment by cjellick** [comment]
I think scripts/package should rewritten to produce the image so that by default just `make` will output an image, like longhorn.

What do you think @yasker ?

**Comment by yasker** [comment]
Sure, that's my preference as well. Will add that part.

**Comment by yasker** [comment]
@cjellick Updated, merged `image` into `package`.

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
